project_id = "ucpsiqmsxocwasorvojw"

[functions.bible]
verify_jwt = false

[functions.generate-verse-image]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-theme-image]
verify_jwt = false

[functions.send-daily-challenge-reminder]
verify_jwt = false
