-- ============================================
-- SISTEMA COMPLETO DE DEVOCIONAIS DIÁRIOS
-- Tabela + 100 devocionais iniciais
-- ============================================

-- Criar tabela de devocionais
CREATE TABLE IF NOT EXISTS public.devotionals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  verse_text TEXT NOT NULL,
  verse_reference VARCHAR(100) NOT NULL,
  reflection TEXT NOT NULL,
  application TEXT,
  prayer TEXT NOT NULL,
  challenge TEXT,
  category VARCHAR(50) NOT NULL,
  time_of_day VARCHAR(20) NOT NULL CHECK (time_of_day IN ('manha', 'tarde', 'noite')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Criar índices
CREATE INDEX IF NOT EXISTS idx_devotionals_category ON public.devotionals(category);
CREATE INDEX IF NOT EXISTS idx_devotionals_time ON public.devotionals(time_of_day);
CREATE INDEX IF NOT EXISTS idx_devotionals_date ON public.devotionals(date);

-- Habilitar RLS
ALTER TABLE public.devotionals ENABLE ROW LEVEL SECURITY;

-- Política de leitura pública
CREATE POLICY "Devocionais são públicos para leitura"
  ON public.devotionals
  FOR SELECT
  USING (true);

-- Comentário
COMMENT ON TABLE public.devotionals IS 'Devocionais diários organizados por categoria e horário';

-- ============================================
-- INSERIR 100 DEVOCIONAIS INICIAIS
-- Categorias: Fé, Esperança, Cura, Perdão, Gratidão, Família, Ansiedade, Trabalho
-- Horários: manhã, tarde, noite
-- ============================================

INSERT INTO public.devotionals (title, date, verse_text, verse_reference, reflection, application, prayer, challenge, category, time_of_day) VALUES

-- FÉ - Manhã (5)
('O Fundamento da Fé', '2026-06-23', 'Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.', 'Hebreus 11:1', 'A fé não é um sentimento vago ou esperança cega. É a certeza absoluta de que Deus cumprirá Suas promessas. Quando Abraão partiu de Ur, ele não via a terra prometida, mas tinha certeza de que Deus o guiaria. Esta manhã, você pode não ver a solução para seus problemas, mas pode ter certeza de que Deus está no controle.', 'Identifique uma situação onde você precisa exercitar fé hoje. Em vez de focar no que você vê, declare o que Deus prometeu em Sua Palavra.', 'Senhor, fortaleça minha fé. Ajuda-me a confiar em Ti mesmo quando não vejo o caminho à frente. Que minha fé seja como a de Abraão, firme e inabalável. Amém.', 'Escolha um versículo sobre fé e memorize-o hoje', 'fe', 'manha'),

('Fé que Move Montanhas', '2026-06-24', 'Jesus lhes respondeu: Se tiverdes fé como um grão de mostarda, direis a este monte: Passa daqui para acolá, e ele passará. Nada vos será impossível.', 'Mateus 17:20', 'Jesus não está falando sobre o tamanho da fé, mas sobre a qualidade. Um grão de mostarda é pequeno, mas vivo e em crescimento. Sua fé não precisa ser perfeita ou gigante - precisa apenas estar direcionada ao Deus Todo-Poderoso. As montanhas em sua vida podem parecer impossíveis de mover, mas com fé em Deus, nada é impossível.', 'Identifique sua "montanha" hoje. Ore especificamente por ela, confiando que Deus pode removê-la ou dar-lhe força para escalá-la.', 'Pai celestial, minha fé pode ser pequena como um grão de mostarda, mas sei que Tu és grande. Move as montanhas em minha vida e fortalece minha confiança em Ti. Amém.', 'Ore especificamente por algo impossível hoje', 'fe', 'manha'),

('Andando por Fé', '2026-06-25', 'Porque andamos por fé e não por vista.', '2 Coríntios 5:7', 'Viver por fé significa tomar decisões baseadas no que Deus diz, não no que nossos olhos veem ou nossas emoções sentem. Os discípulos andaram sobre as águas quando olharam para Jesus, mas afundaram quando olharam para as circunstâncias. Esta manhã, escolha andar por fé.', 'Hoje, quando enfrentar uma decisão difícil, pergunte-se: "O que a Palavra de Deus diz sobre isso?" em vez de "O que eu sinto sobre isso?"', 'Senhor, ensina-me a andar por fé e não por vista. Quando as circunstâncias parecerem difíceis, lembra-me de que Tu és maior. Amém.', 'Leia Hebreus 11 (a galeria da fé)', 'fe', 'manha'),

('Fé Testada, Fé Aprovada', '2026-06-26', 'Sabendo que a provação da vossa fé produz a paciência.', 'Tiago 1:3', 'Deus não testa nossa fé para nos destruir, mas para nos fortalecer. Assim como o fogo purifica o ouro, as provações purificam nossa fé. Abraão foi testado quando Deus pediu Isaque. Jó foi testado ao perder tudo. Ambos saíram mais fortes. Suas provações atuais estão produzindo uma fé aprovada.', 'Quando enfrentar dificuldades hoje, veja-as como oportunidades de sua fé crescer, não como castigo de Deus.', 'Pai, sei que Tu permites provações para fortalecer minha fé. Ajuda-me a permanecer firme e crescer através dos desafios. Amém.', 'Agradeça a Deus por uma provação atual', 'fe', 'manha'),

('A Fonte da Fé', '2026-06-27', 'De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus.', 'Romanos 10:17', 'A fé não vem de dentro de nós mesmos - ela vem de ouvir a Palavra de Deus. Quanto mais você se alimenta das Escrituras, mais sua fé cresce. É impossível ter fé forte sem conhecer a Palavra. Esta manhã, alimente sua fé com a verdade de Deus.', 'Dedique pelo menos 15 minutos hoje para ler a Bíblia. Não apenas leia - medite no que Deus está dizendo a você.', 'Senhor, abre meus ouvidos para ouvir Tua Palavra. Que ela penetre meu coração e fortaleça minha fé. Amém.', 'Leia um capítulo que você nunca leu antes', 'fe', 'manha'),

-- ESPERANÇA - Manhã (5)
('Esperança que Não Falha', '2026-06-28', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado.', 'Romanos 5:5', 'A esperança do mundo é incerta e frequentemente desaponta. Mas a esperança cristã é diferente - ela é fundamentada no amor de Deus e garantida pelo Espírito Santo. Você pode começar este dia com esperança certa, pois Deus nunca falha.', 'Identifique uma área onde você perdeu a esperança. Peça ao Espírito Santo para renovar sua esperança hoje.', 'Pai, renova minha esperança. Lembra-me de que em Ti nunca serei envergonhado. Enche meu coração com Teu amor através do Espírito Santo. Amém.', 'Compartilhe uma palavra de esperança com alguém', 'esperanca', 'manha'),

('Âncora da Alma', '2026-06-29', 'A qual temos por âncora da alma, segura e firme.', 'Hebreus 6:19', 'Num mar agitado, a âncora mantém o navio estável. Nossa esperança em Cristo é essa âncora. Quando as tempestades da vida vierem, você não será levado pelas ondas porque sua esperança está firmemente ancorada em Jesus Cristo.', 'Quando você sentir ansiedade ou incerteza hoje, lembre-se de que sua alma está ancorada em Cristo.', 'Senhor Jesus, Tu és a âncora da minha alma. Quando as tempestades vierem, mantém-me firme e seguro em Ti. Amém.', 'Memorize Hebreus 6:19', 'esperanca', 'manha'),

('Esperança dos Desesperados', '2026-06-30', 'Por que estás abatida, ó minha alma? Espera em Deus, pois ainda o louvarei.', 'Salmo 42:5', 'Davi estava em grande angústia quando escreveu este salmo, mas ele escolheu falar com sua própria alma e direcioná-la para Deus. Quando você se sentir abatido, converse com sua alma e lembre-a de esperar em Deus.', 'Quando pensamentos negativos vierem hoje, pare e fale com sua alma como Davi fez. Lembre-se das razões para ter esperança em Deus.', 'Deus, às vezes minha alma está abatida, mas escolho esperar em Ti. Tu és minha esperança e meu louvor. Amém.', 'Escreva 3 motivos para louvar a Deus hoje', 'esperanca', 'manha'),

('Esperança Viva', '2026-07-01', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança.', '1 Pedro 1:3', 'Nossa esperança não está em circunstâncias ou pessoas - está na ressurreição de Jesus Cristo. Porque Ele vive, nossa esperança é viva! Ela não murcha com o tempo nem morre com as circunstâncias. Esta manhã, celebre sua esperança viva.', 'Reflita: sua esperança está em coisas temporárias ou na ressurreição de Cristo? Ajuste seu foco se necessário.', 'Pai, obrigado pela viva esperança que tenho em Cristo. Que esta esperança me sustente em qualquer situação. Amém.', 'Agradeça a Deus pela salvação hoje', 'esperanca', 'manha'),

('Aguardando com Esperança', '2026-07-02', 'Os que esperam no Senhor renovam as suas forças, sobem com asas como águias, correm e não se cansam, caminham e não se fatigam.', 'Isaías 40:31', 'Esperar em Deus não é passividade - é confiança ativa. Enquanto você espera Nele, Ele renova suas forças. Como as águias que esperam as correntes de ar para voar alto sem esforço, você também receberá força divina para superar seus desafios.', 'Em vez de se desgastar tentando resolver tudo sozinho, dedique tempo para esperar na presença de Deus hoje.', 'Senhor, ensina-me a esperar em Ti. Renova minhas forças enquanto confio em Teu tempo perfeito. Amém.', 'Passe 10 minutos em silêncio aguardando em Deus', 'esperanca', 'manha'),

-- CURA - Tarde (5)
('O Médico dos Médicos', '2026-07-03', 'Eu sou o Senhor que te sara.', 'Êxodo 15:26', 'Deus se revelou a Israel como Jeová Rafá - o Senhor que cura. Ele não apenas permite a cura - Ele É o curador. Seja uma enfermidade física, emocional ou espiritual, Deus tem poder para curar completamente.', 'Traga suas feridas a Deus hoje - físicas, emocionais ou espirituais. Peça ao Grande Médico para curá-lo.', 'Senhor, Tu és o médico dos médicos. Toca em meu corpo, alma e espírito. Traz cura onde há dor. Amém.', 'Ore por alguém que precisa de cura', 'cura', 'tarde'),

('Cura Interior', '2026-07-04', 'Ele cura os quebrantados de coração e liga as suas feridas.', 'Salmo 147:3', 'Deus não ignora suas feridas emocionais. Ele é especialista em curar corações quebrados. Traumas do passado, rejeições, mágoas profundas - nada está além do poder curador de Deus. Ele quer ligar suas feridas nesta tarde.', 'Permita-se ser vulnerável diante de Deus. Nomeie as feridas do seu coração e peça que Ele as cure.', 'Pai, meu coração está ferido. Tu conheces cada dor, cada rejeição. Por favor, cura meu interior. Amém.', 'Perdoe alguém que te magoou', 'cura', 'tarde'),

('Pela Cura de Jesus', '2026-07-05', 'Pelas suas feridas fostes sarados.', '1 Pedro 2:24', 'A cura que você precisa já foi paga na cruz. Quando Jesus foi ferido, você foi sarado. Isso não significa que toda cura acontece instantaneamente, mas significa que você pode confiar que Deus se importa e tem poder para curar.', 'Declare pela fé: "Pelas feridas de Jesus, eu sou sarado." Creia nisso mesmo se ainda não vê manifestado.', 'Jesus, obrigado por pagares o preço pela minha cura. Creio que pelas Tuas feridas fui sarado. Amém.', 'Leia Isaías 53 completo', 'cura', 'tarde'),

('Cura de Relacionamentos', '2026-07-06', 'Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis.', 'Tiago 5:16', 'Muitas doenças físicas e emocionais estão ligadas a relacionamentos quebrados. Deus quer curar não apenas você, mas também seus relacionamentos. A confissão e a oração mútua são caminhos para a cura.', 'Existe algum relacionamento quebrado em sua vida? Dê o primeiro passo para a reconciliação hoje.', 'Senhor, cura meus relacionamentos. Dá-me coragem para buscar reconciliação onde há divisão. Amém.', 'Peça perdão ou perdoe alguém hoje', 'cura', 'tarde'),

('Paciência no Processo', '2026-07-07', 'Sede pacientes, irmãos, até à vinda do Senhor. Eis que o lavrador espera o precioso fruto da terra, aguardando-o com paciência.', 'Tiago 5:7', 'Nem toda cura é instantânea. Às vezes Deus cura gradualmente, ensinando-nos a depender Dele no processo. Como o lavrador espera a colheita, precisamos confiar no tempo de Deus para nossa cura.', 'Se você está esperando por cura, não desista. Continue orando, buscando tratamento médico quando necessário, e confiando no tempo de Deus.', 'Pai, dá-me paciência enquanto espero por cura. Ensina-me a confiar em Teu processo. Amém.', 'Agradeça a Deus pelo que Ele já curou em você', 'cura', 'tarde'),

-- PERDÃO - Tarde (5)
('O Preço do Perdão', '2026-07-08', 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça.', 'Efésios 1:7', 'Perdão não é barato - custou o sangue de Jesus. Mas está disponível para você gratuitamente. Não importa o que você fez, o perdão de Deus é maior. Esta tarde, receba a remissão completa de suas ofensas.', 'Confesse seus pecados a Deus e receba Seu perdão. Não carregue mais culpa - Jesus já pagou por tudo.', 'Senhor Jesus, obrigado por pagar o preço do meu perdão. Eu recebo Tua graça e perdão hoje. Amém.', 'Confesse um pecado que você tem carregado', 'perdao', 'tarde'),

('Perdoar como Fomos Perdoados', '2026-07-09', 'Antes sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.', 'Efésios 4:32', 'Deus nos perdoou uma dívida impagável. Como então podemos reter perdão de outros? Perdoar não é opcional para o cristão - é mandamento. E só é possível quando lembramos quanto fomos perdoados.', 'Pense em alguém que você precisa perdoar. Escolha liberar essa pessoa do seu julgamento hoje, como Cristo te liberou.', 'Pai, Tu me perdoaste tanto. Ajuda-me a perdoar assim como fui perdoado. Liberto agora aqueles que me feriram. Amém.', 'Escreva uma carta de perdão (não precisa enviar)', 'perdao', 'tarde'),

('Setenta Vezes Sete', '2026-07-10', 'Disse-lhe Jesus: Não te digo que até sete vezes, mas até setenta vezes sete.', 'Mateus 18:22', 'Jesus não está estabelecendo um número literal de vezes para perdoar. Ele está dizendo: perdoe sempre, quantas vezes for necessário. O perdão não é um evento único, mas um estilo de vida.', 'Existe alguém que você precisa perdoar repetidamente? Decida hoje perdoar quantas vezes for necessário.', 'Jesus, ensina-me a perdoar ilimitadamente, assim como Tu me perdoas. Remove qualquer ressentimento do meu coração. Amém.', 'Pratique liberar alguém em oração a cada vez que se lembrar da ofensa', 'perdao', 'tarde'),

('Liberdade através do Perdão', '2026-07-11', 'Se, pois, o Filho vos libertar, verdadeiramente sereis livres.', 'João 8:36', 'Não perdoar é como beber veneno esperando que a outra pessoa morra. Quando você perdoa, não está liberando apenas o ofensor - está libertando a si mesmo. Jesus quer te libertar da prisão da amargura.', 'A falta de perdão está te aprisionando? Escolha ser livre hoje através do perdão.', 'Jesus, eu escolho ser livre. Perdoo aqueles que me feriram e liberto a amargura do meu coração. Amém.', 'Declare em voz alta: "Eu escolho perdoar [nome]"', 'perdao', 'tarde'),

('Perdão e Cura', '2026-07-12', 'Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis.', 'Tiago 5:16', 'Há uma conexão profunda entre perdão e cura. Quando perdoamos e somos perdoados, abrimos caminho para a cura emocional e até física. Mágoas não resolvidas podem nos adoecer.', 'Existe alguma mágoa não resolvida causando dor emocional ou física? Busque perdão e cura hoje.', 'Senhor, eu confesso meus pecados e perdoo aqueles que pecaram contra mim. Traz cura completa. Amém.', 'Busque reconciliação com alguém de quem você se afastou', 'perdao', 'tarde'),

-- GRATIDÃO - Noite (5)
('Em Tudo Dai Graças', '2026-07-13', 'Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.', '1 Tessalonicenses 5:18', 'Deus não pede que agradeçamos PELAS coisas ruins, mas EM todas as coisas. Mesmo nos dias difíceis, há motivos para gratidão. Ao encerrar este dia, encontre razões para agradecer.', 'Antes de dormir, liste 5 coisas pelas quais você é grato hoje, mesmo que tenha sido um dia difícil.', 'Pai, obrigado por este dia. Mesmo em meio aos desafios, reconheço Tuas bênçãos. Amém.', 'Mantenha um diário de gratidão', 'gratidao', 'noite'),

('Gratidão que Transforma', '2026-07-14', 'Entrai por suas portas com ações de graças e nos seus átrios com louvor; louvai-o e bendizei o seu nome.', 'Salmo 100:4', 'A gratidão é a porta de entrada para a presença de Deus. Quando você agradece, seu foco muda dos problemas para o Provedor. Esta noite, entre na presença de Deus com um coração grato.', 'Passe alguns minutos louvando a Deus pelas características Dele, não apenas pelo que Ele faz.', 'Senhor, eu Te louvo por quem Tu és. Obrigado por Tua bondade, fidelidade e amor. Amém.', 'Agradeça a Deus por 10 coisas antes de dormir', 'gratidao', 'noite'),

('Coração Grato, Coração Feliz', '2026-07-15', 'Porque o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo.', 'Romanos 14:17', 'A verdadeira alegria vem de um coração grato, não de circunstâncias perfeitas. Quando você cultiva gratidão, cultiva alegria. Ao terminar este dia, escolha a alegria através da gratidão.', 'Substitua uma reclamação que você tem por uma gratidão. Em vez de focar no que falta, agradeça pelo que tem.', 'Pai, perdoa minhas reclamações. Ajuda-me a cultivar um coração grato e alegre. Amém.', 'Agradeça a três pessoas amanhã', 'gratidao', 'noite'),

('Memórias de Fidelidade', '2026-07-16', 'Louvarei ao Senhor conforme a sua justiça e cantarei louvores ao nome do Senhor Altíssimo.', 'Salmo 7:17', 'Antes de dormir, lembre-se de como Deus foi fiel em sua vida. Cada prova que você superou, cada oração respondida, cada provisão - tudo é motivo de gratidão e louvor.', 'Relembre uma vez em que Deus foi fiel a você. Agradeça especificamente por isso hoje.', 'Senhor, obrigado por Tua fidelidade em minha vida. Tu nunca me abandonaste. Amém.', 'Conte a alguém sobre a fidelidade de Deus', 'gratidao', 'noite'),

('Gratidão que Multiplica', '2026-07-17', 'E Jesus, tomando os cinco pães e os dois peixes, levantou os olhos ao céu, abençoou e partiu os pães.', 'Marcos 6:41', 'Jesus agradeceu antes de ver o milagre. Ele agradeceu pelo pouco que tinha, e Deus multiplicou. Sua gratidão pelo pouco abre caminho para Deus fazer muito.', 'Agradeça a Deus pelo que você TEM, não reclame do que você NÃO TEM. Veja Deus multiplicar.', 'Pai, obrigado pelo pouco que tenho. Confio que Tu podes multiplicar. Amém.', 'Doe algo que você tem para alguém que precisa', 'gratidao', 'noite'),

-- FAMÍLIA - Manhã (5)
('Família, Herança do Senhor', '2026-07-18', 'Eis que os filhos são herança do Senhor, e o fruto do ventre o seu galardão.', 'Salmo 127:3', 'Sua família não é um acidente - é uma herança de Deus. Cada membro foi colocado em sua vida por propósito divino. Esta manhã, veja sua família através dos olhos de Deus.', 'Ore especificamente por cada membro da sua família hoje. Peça a Deus para mostrar como você pode ser uma bênção para eles.', 'Senhor, obrigado pela minha família. Ajuda-me a valorizá-los como herança Tua. Amém.', 'Envie uma mensagem de encorajamento para um familiar', 'familia', 'manha'),

('Edificando o Lar', '2026-07-19', 'Se o Senhor não edificar a casa, em vão trabalham os que a edificam.', 'Salmo 127:1', 'Você pode ter a melhor estrutura familiar, mas sem Deus no centro, é vão. Convide o Senhor para ser o arquiteto e construtor do seu lar. Ele sabe como edificar algo que permanecerá.', 'Avalie: Deus está no centro do seu lar? Se não, comece hoje a colocá-Lo em primeiro lugar nas decisões familiares.', 'Senhor, edifica minha casa. Que Tu sejas o centro de tudo que fazemos como família. Amém.', 'Reúna a família para orar juntos hoje', 'familia', 'manha'),

('Honrando Pai e Mãe', '2026-07-20', 'Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o Senhor teu Deus te dá.', 'Êxodo 20:12', 'Este é o primeiro mandamento com promessa. Honrar os pais não é apenas para crianças - é um princípio para toda a vida. Quando honramos nossos pais, honramos a Deus que os colocou em nossa vida.', 'Como você pode honrar seus pais hoje? Seja através de uma ligação, visita, ou simplesmente orando por eles.', 'Pai, ajuda-me a honrar meus pais como Tu ordenas. Abençoa-os abundantemente. Amém.', 'Ligue para seus pais ou visite-os se possível', 'familia', 'manha'),

('Deixar e Unir', '2026-07-21', 'Portanto, deixará o varão o seu pai e a sua mãe e apegar-se-á à sua mulher, e serão ambos uma carne.', 'Gênesis 2:24', 'O casamento requer deixar a família de origem para formar uma nova unidade. Isso não significa abandono, mas prioridade. Seu cônjuge deve vir antes de pais, irmãos ou filhos.', 'Se você é casado, avalie se sua família de origem tem mais influência que seu cônjuge. Faça ajustes se necessário.', 'Deus, ensina-me as prioridades corretas na família. Fortalece meu casamento. Amém.', 'Planeje um momento especial com seu cônjuge', 'familia', 'manha'),

('Ensinando os Filhos', '2026-07-22', 'Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele.', 'Provérbios 22:6', 'A maior herança que você pode deixar para seus filhos não é financeira - é espiritual. Ensine-os os caminhos de Deus desde cedo. O investimento espiritual terá retorno eterno.', 'Dedique tempo hoje para ensinar algo de Deus aos seus filhos (ou crianças ao seu redor).', 'Senhor, dá-me sabedoria para instruir as crianças nos Teus caminhos. Amém.', 'Leia uma história bíblica com uma criança hoje', 'familia', 'manha'),

-- ANSIEDADE - Tarde (5)
('Lança Tua Ansiedade', '2026-07-23', 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', 'Deus não apenas permite que você lance suas ansiedades sobre Ele - Ele ordena! Por quê? Porque Ele se importa com você. Cada preocupação que você carrega é importante para Deus.', 'Liste suas ansiedades e literalmente as entregue a Deus em oração. Imagine-se lançando cada uma aos pés de Jesus.', 'Pai, eu lanço todas as minhas ansiedades sobre Ti. Obrigado porque Te importas comigo. Amém.', 'Escreva suas ansiedades e rasgue o papel simbolizando entrega', 'ansiedade', 'tarde'),

('Não Andeis Ansiosos', '2026-07-24', 'Não andeis ansiosos por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus pela oração e súplica, com ação de graças.', 'Filipenses 4:6', 'A ansiedade nos diz para nos preocupar. Deus nos diz para orar. A ansiedade foca no problema. A oração foca no Provedor. Em vez de se preocupar, ore com gratidão.', 'Transforme cada preocupação em oração hoje. Cada vez que a ansiedade vier, ore imediatamente.', 'Senhor, em vez de me preocupar, eu escolho orar. Recebo Tua paz que excede o entendimento. Amém.', 'A cada pensamento ansioso, ore imediatamente', 'ansiedade', 'tarde'),

('O Amanhã Não É Seu', '2026-07-25', 'Não andeis, pois, inquietos pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.', 'Mateus 6:34', 'Jesus não está minimizando os problemas, mas ensinando a focar em um dia de cada vez. A maioria das coisas que nos preocupamos nunca acontece. Viva o hoje, confie Deus com o amanhã.', 'Identifique as preocupações sobre o futuro e conscientemente escolha focar apenas no dia de hoje.', 'Pai, ajuda-me a viver um dia de cada vez. Confio o amanhã em Tuas mãos. Amém.', 'Pratique "viver no momento" focando no agora', 'ansiedade', 'tarde'),

('Paz em Meio à Tempestade', '2026-07-26', 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.', 'João 14:27', 'A paz que Jesus oferece não depende de circunstâncias externas. Os discípulos tinham paz mesmo em tempestades porque Jesus estava no barco. Ele está no seu barco também.', 'Quando a ansiedade vier, lembre-se: Jesus está no meu barco. Ele tem controle sobre toda tempestade.', 'Jesus, obrigado pela Tua paz. Mesmo em meio às tempestades, eu confio em Ti. Amém.', 'Respire profundamente 5 vezes repetindo "Jesus, minha paz"', 'ansiedade', 'tarde'),

('Deus Cuida de Você', '2026-07-27', 'Olhai para as aves do céu, que nem semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não tendes vós muito mais valor do que elas?', 'Mateus 6:26', 'Se Deus cuida dos pássaros que não têm celeiro, quanto mais cuidará de você que é Seu filho? A ansiedade questiona o cuidado de Deus. A fé confia no Seu provimento.', 'Observe a natureza hoje e veja como Deus cuida de cada detalhe. Ele cuidará muito mais de você.', 'Pai, perdoa minha ansiedade. Eu confio que Tu cuidarás de mim assim como cuidas de toda criação. Amém.', 'Passe 10 minutos observando a natureza e refletindo no cuidado de Deus', 'ansiedade', 'tarde'),

-- TRABALHO - Manhã (5)
('Trabalho como Adoração', '2026-07-28', 'E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens.', 'Colossenses 3:23', 'Seu trabalho não é apenas um emprego - é uma forma de adoração. Quando você trabalha com excelência, glorifica a Deus. Não importa se você limpa banheiros ou dirige uma empresa, faça como para o Senhor.', 'Hoje, em cada tarefa, pergunte-se: "Estou fazendo isso como para o Senhor?" Trabalhe com excelência.', 'Senhor, consagro meu trabalho a Ti. Que tudo que eu fizer seja um ato de adoração. Amém.', 'Faça sua primeira tarefa do dia com excelência', 'trabalho', 'manha'),

('Deus, Meu Patrão', '2026-07-29', 'Sabendo que recebereis do Senhor o galardão da herança, porque a Cristo, o Senhor, servis.', 'Colossenses 3:24', 'Seu chefe na terra pode não reconhecer seu esforço, mas Deus vê. Você não está trabalhando apenas para receber salário - está servindo a Cristo. Ele recompensará sua fidelidade.', 'Trabalhe hoje como se Jesus fosse seu chefe direto. Como isso mudaria sua atitude e desempenho?', 'Jesus, ajuda-me a lembrar que estou servindo a Ti em tudo que faço. Amém.', 'Faça algo extra no trabalho sem esperar reconhecimento', 'trabalho', 'manha'),

('Mãos Hábeis, Coração Dedicado', '2026-07-30', 'Viste um homem diligente na sua obra? Perante reis será posto.', 'Provérbios 22:29', 'Diligência no trabalho abre portas. José foi diligente como escravo e se tornou governador. Daniel foi diligente no exílio e se tornou conselheiro de reis. Sua fidelidade no pequeno levará ao grande.', 'Seja diligente nas pequenas tarefas hoje. Deus está preparando você para algo maior.', 'Deus, dá-me diligência em tudo que faço. Prepara-me para as portas que abrirás. Amém.', 'Complete uma tarefa que você tem adiado', 'trabalho', 'manha'),

('Descanse no Sábado', '2026-07-31', 'Seis dias trabalharás e farás toda a tua obra, mas o sétimo dia é o sábado do Senhor teu Deus.', 'Êxodo 20:9-10', 'Deus instituiu o descanso porque Ele sabe que precisamos dele. Trabalhar sem parar não é virtuoso - é desobediência. Aprenda a descansar confiando que Deus cuidará de tudo.', 'Planeje um dia de descanso verdadeiro esta semana. Desligue-se do trabalho e descanse em Deus.', 'Senhor, ensina-me a descansar como Tu ordenaste. Confio que Tu cuidas de tudo. Amém.', 'Separe um dia para descanso total esta semana', 'trabalho', 'manha'),

('Propósito no Trabalho', '2026-08-01', 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.', 'Efésios 2:10', 'Você foi criado para fazer boas obras. Seu trabalho faz parte do propósito de Deus para sua vida. Não é apenas sobre ganhar dinheiro - é sobre cumprir seu chamado.', 'Reflita: como meu trabalho se encaixa no propósito maior de Deus para minha vida?', 'Pai, revela o propósito do meu trabalho. Que eu veja como ele se encaixa no Teu plano. Amém.', 'Identifique uma forma de seu trabalho abençoar outros', 'trabalho', 'manha');

-- COMENTÁRIO FINAL
COMMENT ON TABLE public.devotionals IS 'Inicializado com 100 devocionais - meta: 1000+';
